import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { UserProvider } from "@/context/userContext";
import { SocketProvider } from "@/context/socketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "coffee chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
        <SocketProvider>
        {children}
        <Toaster />
        </SocketProvider>
          </UserProvider>
      </body>
        
    </html>
  );
}
